# Use root/example as user/password credentials
version: "3.1"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/courses?allowPublicKeyRetrieval=true
    networks:
      - springapimysql-net
    depends_on:
      - db
    volumes:
      - .m2:/root/.m2
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_courses
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - springapimysql-net
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./src/test/resources/mysql-docker/sql_scripts/courses_init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/test/resources/mysql-docker/sql_scripts/courses_schema.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./src/test/resources/mysql-docker/sql_scripts/courses_insert.sql:/docker-entrypoint-initdb.d/3.sql"
networks:
  springapimysql-net: